# http server port that provides services externally
http_server_port: 8080

# rpc server port that provides services externally
rpc_server_port: 8081

# the path of leveldb that stores blockchain
leveldb_path: "."

# peer type, 0:FULL 1:Miner 2:SPV
type: 1

# peer port
port: 3006

# peer exposed endpoint
endpoint: localhost:3006

# bootstrap peers
bootstrap_peers:
  #- "localhost:3007"

# peer sync block interval
block_sync_interval: 0

# address to receive coinbase reward
reward_address: "1QCZvtyk5YeqxXVuqDZNa9toxiP1icDW1f"